### ISSUE TITLE
Change C# Code

### ISSUE THREAD

**Issue by Milan-Hurban** [industrial-edge/pingpong-csharp#11]
Hi, I tried this example and it doesn't work out-of-the-box, as the client tries to connect to the broker without using the username and password, which of course doesn't work. The correct line (181) is commented out. I haven't seen it mentioned and it took me a while to find the issue, so maybe change that for the next version.

Thanks!

**Comment by HummelN7872** [comment]
@EvaKaul  please double check the issue mentioned by Milan

**Comment by EvaKaul** [comment]
fixed with merge on 28.02.2023
