### ISSUE TITLE
Problem testing this App

### ISSUE THREAD

**Issue by KarloX2** [industrial-edge/pingpong-csharp#7]
Hello!

I managed to publish and install this app on my IED. According to the log output it seems to be running. The log includes the lines "Client successfully connected to broker" and "Subscribed topic1" so I assume the MQTT is up and running.

Then I followed your instructions to test the app using the IE Flow Creator (v1.1.2) but it seems to be unable to connect the IE databus (i.e. the MQTT broker):

The message "Verbindung wird hergestellt..." (= "establishing connection...") persists and never completes. For the server name, I tried with "ie_databus" like in your video. I also tried "ie-databus" (with a hyphen, like found in some other document) as well as my local IED ip address. Nothing seems to work. How can I resolve this? Also I find no way how to install the IE Databus Configurator App. It's in my IE catalog but there's simply no function offered to install it on the IED so I can't use it.

Thanks!

![clip1](https://user-images.githubusercontent.com/15713553/135421378-01ff1be8-2dbd-4170-928f-d1aabd378840.PNG)
![clip2](https://user-images.githubusercontent.com/15713553/135421426-40f54933-3dff-4f4b-9d56-65d0853931b0.PNG)

**Comment by Boehmi-TB** [comment]
HI KarloX2,
I would recommend using "ie-databus", "ie_databus" does still work but is deprecated and might not work in the future.
in the menu point "Sicherheit" (Security) you need to enter the credentials (username and password) for accessing IE-Databus. 

The User needs to first created in IE Databus Configurator and granted the access rights to the topics.
The IE Databus is centrally configured from Industrial Edge Management, so the Configurator you can find there
![image](https://user-images.githubusercontent.com/74045802/135449095-dbaf8ea1-4cfe-44d1-abec-324760313637.png)

The Configurator needs to be first installed on the Industrial Edge Management. This you can to by accessing Edge Management as following: https://iem-ip
![image](https://user-images.githubusercontent.com/74045802/135449422-f34536f4-23fd-4ecb-85ee-dcbc358003de.png)

**Comment by KarloX2** [comment]
@Boehmi-TB Thanks, that did the trick.
